name: Build Font (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Extract FontForge (zip)
        run: |
          Expand-Archive -Path .\FontForgeBuilds.zip -DestinationPath C:\FontForge

      - name: Run fontforge script
        run: |
          & 'C:\FontForge\bin\ffpython.exe' .\fontforge_script.py

      - name: Run fonttools script
        run: python .\fonttools_script.py
